spring:
  data:
    redis:
      port: 6379
      host: localhost
      password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentms?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: 18937260063@163.com
    password: VGZUOSMZLBMLMHDI
    #   password: JTHHDRHMRSCNTXBY
    default-encoding: UTF-8
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
server:
  port: 8080
